### PR TITLE
fix: Self-issue Internet PKI certificate for gRPC server

### LINKED ISSUE #36: Self-issue Internet PKI certificate for gRPC server
Requirements:

- Use RSA 2048 + SHA-256.
- `subjectAltName` extension set to the IP address `192.168.0.1` (@sdsantos: is it safe to hard code this value? or can this IP address be different?)
- `basicConstraints` extension should mark the subject as not a CA.
- Expiry date should be short-lived -- In the order of days or weeks. This means the certificate and its key pair should be regenerated periodically.

### PR DESCRIPTION
**Pull request by gnarea**
Fixes #36

Adding Bouncy Castle introduces many Lint violation warnings like:

```
Error processing /home/gus/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcpkix-jdk15on/1.65/c9507d93e4b453320b57d9ac21bdd67d65a00bbc/bcpkix-jdk15on-1.65.jar:META-INF/versions/9/module-info.class: broken class file? (This feature requires ASM6)
Error processing /home/gus/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.65/320b989112f00a63a3bcfa5a98f31a4f865a20fa/bcprov-jdk15on-1.65.jar:META-INF/versions/11/org/bouncycastle/jcajce/provider/asymmetric/edec/KeyFactorySpi.class: broken class file? (This feature requires ASM7)
```

There are a bunch of solutions here: https://stackoverflow.com/questions/60598110/meta-inf-versions-9-module-info-class-broken-class-file-this-feature-requires -- any preference? I don't like any -- it seems like a matter of picking a poison.

### CODE REVIEW

File: app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo
+import org.bouncycastle.cert.X509CertificateHolder
+import org.bouncycastle.cert.X509v3CertificateBuilder
+import org.bouncycastle.crypto.params.AsymmetricKeyParameter
+import org.bouncycastle.crypto.util.PrivateKeyFactory
+import org.bouncycastle.operator.ContentSigner
+import org.bouncycastle.operator.DefaultDigestAlgorithmIdentifierFinder
+import org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder
+import org.bouncycastle.operator.bc.BcRSAContentSignerBuilder
+import org.bouncycastle.util.encoders.Base64
```
Comment (gnarea) [inline app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt:18]: I discovered this little gem by chance... Since we have to use BC anyway, what do you think if I replace the use of the Apache library with this?

Comment (sdsantos) [reply app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt:18]: Fine by me

File: app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+
+    private fun derToPem(valueDer: ByteArray, pemLabel: String): ByteArray {
+        val valueBase64 = Base64.toBase64String(valueDer)
+        val valuePem = "-----BEGIN $pemLabel-----\n${valueBase64}\n-----END $pemLabel-----"
+        return valuePem.toByteArray()
+    }
+
+    companion object {
+        private const val RSA_KEY_MODULUS = 2048
+        const val SUBJECT_IP_ADDRESS = "192.168.43.1"
```
Comment (sdsantos) [inline app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt:44]: I was meaning to check this before, but it seems that we can't trust the IP to always be `192.168.43.1`. Most of the times it will be, but some more recent devices are picking an IP address randomly inside `192.168.43.X`.

File: app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt [hunk 3]
```diff
@@ -45,14 +43,19 @@ internal constructor(
         withContext(Dispatchers.IO) {
             setupTLSProvider()
 
+            val certGenerator = TLSCertificateGenerator.generate()
```
Comment (sdsantos) [inline app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt:46]: Can we inject this somehow through the constructor, or at least make it internally swappable? It would make future testing easier.

File: app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt (hunk 2 above)
Comment (gnarea) [reply app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt:44]: Indeed, I forgot to mention I discovered that yesterday: https://stackoverflow.com/questions/61615270/how-to-get-the-ip-address-of-the-default-gateway-reliably-on-android-5

From the testing I did, the certificate can have this IP address even if it's wrong, as long as the client disables hostname verification.

File: app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt (hunk 3 above)
Comment (gnarea) [reply app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt:46]: What do you mean by internally swappable?

I did consider moving `TLSCertificateGenerator.generate()` to a lazily-initialised field because I thought that in the future we might not want to use TLS (during local dev), but I forgot to follow through.

File: app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt (hunk 2 above)
Comment (gnarea) [reply app/src/main/java/tech/relaycorp/cogrpc/server/TLSCertificateGenerator.kt:44]: BTW, I added a note to one of the tickets in the Android Gateway to look into this, but I think it's OK in the courier. Worst case scenario, we'd have to require users of the Android Gateway to use DHCP when connecting to the courier, which is what 99% of them would do anyway.

File: app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt (hunk 3 above)
Comment (sdsantos) [reply app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt:46]: Internally swappable would be to make the generator an `internal var` that can be swapped. For example:
```
internal var tlsCertificateGeneratorProvider: (() -> CertGenerator) = TLSCertificateGenerator::generate
```

By default it would use what we setup, but in a test we could switch it to another CertGenerator.

Comment (gnarea) [reply app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt:46]: Gotcha. Makes sense :+1: I'll change it.

**Comment by gnarea** [comment]
In addition to the changes requested, I also implemented an change to use the correct IP address when issuing the certificate instead of the hardcoded `192.168.43.1`. This way, gRPC clients won't have to use `grpc.ssl_target_name_override`. See: https://github.com/relaycorp/relaynet-courier-android/pull/44/commits/4e902caa5b20d154ac28b88b14f2975839d86f2a. I'd appreciate your feedback on that change too.

File: app/src/main/java/tech/relaycorp/cogrpc/server/Networking.kt [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+
+    fun getAllLocalIpAddresses(): Array<String> {
+        val localAddresses = mutableListOf<String>()
+        for (networkInterface in NetworkInterface.getNetworkInterfaces().iterator()) {
+            val localInetAddresses = networkInterface.inetAddresses.toList().filter {
+                it.isSiteLocalAddress
+            }
+            localAddresses.addAll(localInetAddresses.map { it.hostAddress })
+        }
+        return localAddresses.toTypedArray()
```
Comment (sdsantos) [inline app/src/main/java/tech/relaycorp/cogrpc/server/Networking.kt:39]: Kotlin has flatMap for flattening maps inside maps, but this is fine too.

Comment (gnarea) [reply app/src/main/java/tech/relaycorp/cogrpc/server/Networking.kt:39]: I like that better, actually! I'll change it.

BTW, I just realised that I used Array here but that seems to be discouraged in Java so I'll change that too to a list.

**Comment by gnarea** [comment]
@sdsantos, I had to make a change after the rebase (https://github.com/relaycorp/relaynet-courier-android/pull/44/commits/541252d771aab9002f4638ffd17857f33426f95b). Can you please check it out when you get a chance?

I hate having to use an external dependency just to do base64 encoding so I'm seriously considering switching to the raw binary serialisation in the near future (https://github.com/relaynet/specs/issues/61).
